# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nightly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
  
    - name: Restore Packages
      run: nuget restore FindImageResolution.sln

    - name: Build solution
      run: msbuild FindImageResolution\FindImageResolution.csproj -t:rebuild -property:Configuration=Release
      
    - name: Package Files
      run: powershell Compress-Archive -Path 'FindImageResolution\bin\Release\FindImageResolutionNET.exe', 'Python\*.ini', 'Python\*.py' -DestinationPath 'FindImageResolutionNET.zip' -Force
         
    - name: Rename to crplugin
      run: ren  FindImageResolutionNET.zip FindImageResolutionNET.crplugin
      
    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: nightly
        draft: false
        prerelease: true
        body: |
          This is a nightly release.
        files: FindImageResolutionNET.crplugin
