# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
  
    - name: Restore Packages
      run: nuget restore FindImageResolution.sln

    - name: Build solution
      run: msbuild FindImageResolution\FindImageResolution.csproj -t:rebuild -property:Configuration=Release
      
    - name: Package Files
      run: powershell Compress-Archive -Path 'FindImageResolution\bin\Release\FindImageResolutionNET.exe', 'Python\*.ini', 'Python\*.py' -DestinationPath 'FindImageResolutionNET.zip' -Force
         
    - name: Rename to crplugin
      run: ren  FindImageResolutionNET.zip FindImageResolutionNET.crplugin
      
    - name: Release
      uses: softprops/action-gh-release@master
      with:
        #body: ${{steps.build_changelog.outputs.changelog}}
        draft: true
        prerelease: false
        files: FindImageResolutionNET.crplugin
